### ISSUE TITLE
VS2019 support

### ISSUE THREAD

**Issue by adamschackart** [aras-p/sizer#11]
PDBFileReader::ReadDebugInfo only reads versions of msdia*.dll up to VS2015.

**Comment by stoopdapoop** [comment]
VS2019 is supported, I'm using VS2022.

Make sure that your msdia140.dll is somewhere that "LoadLibrary" will see it. The most straightforward place is to just put it in the same directory as your sizer executable.

The default path for the DLL is "C:\Program Files\Microsoft Visual Studio\[Year]\[Version]\DIA SDK\bin" for the 32 bit dll. The 64 bit dll is in the AMD64 directory in that same folder.

**Comment by aras-p** [comment]
As of #13 this no longer requires any DIA DLLs at all, so closing this issue.
