### ISSUE TITLE
Strange .text symbols showing up in function list

### ISSUE THREAD

**Issue by hrydgard** [aras-p/sizer#8]
This is the top of the report for PPSSPP: (https://github.com/hrydgard/ppsspp) :

```
Functions by size (kilobytes, min 0.50):
 7652.85: .text$mn                                                                         TestRunner.obj                           .text$mn
  244.64: .text$x                                                                          TestRunner.obj                           .text$x
  153.17: .text                                                                            me_cmp.o                                 .text
  125.71: .text$di                                                                         DinputDevice.obj                         .text$di
   42.82: glewIsSupported                                                                  glew.obj                                 glewIsSupported
```

Any idea what those PE-section-looking things are? TestRunner.cpp is a small file with no functions that include big data or anything like that so it looks odd.

**Comment by aras-p** [comment]
Hmm no idea, never saw that! You are building it with full PDB symbol information, and not just something like "line numbers only"?

**Comment by hrydgard** [comment]
Yeah it's all* "/Zi" (program database).

* The only oddity is that I link with a statically built FFMPEG, built with VS2015, while the rest is built with VS2017, which is built using FFMPEG's tricky build system, not quite sure which flags were passed in.

**Comment by aras-p** [comment]
Yeah no idea, sorry. What the code does is basically go over PDB symbols and sort/categorize them.
